sudo: required
language: java
java:
- 7.0
- 8.0
jdk:
- oraclejdk8
- openjdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
notifications:
  email:
  - one@example.com
deploy:
  provider: heroku
  api_key:
    secure: 3c41289c-8089-4cc7-b04a-a14b95c60a72
  app: danirguez-greeting-java 
  on:
    repo: danirguez/greeting-java